[[annotation]]
file="/home/aak64/rds/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources/gnomad/GRCh38/r2.1.1/gnomad_grch38.AC.AN.AF.sorted.bed.gz"
names=["gnomad_s","gnomad_e","gnomad_ov_id"]
columns=[2,3,4]
ops=["self","self","self"]

[[annotation]]
file="/home/aak64/rds/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources/NGC_V1/GRCh38/20190913/NGC.samples.grch38.sorted.merged.bed.gz"
names=["ngc38_s","ngc38_e","ngc38_ov_id"]
columns=[2,3,4]
ops=["self","self","self"]

[[annotation]]
file="/home/aak64/rds/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources/NGC_V1/GRCh38/NGC.samples.grch37.Lifover.grch38.sorted.merged.bed.gz"
names=["ngclov_s","ngclov_e","ngclov_ov_id"]
columns=[2,3,4]
ops=["self","self","self"]

#[[annotation]]
#file="/home/aak64/rds/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources/ensembl/GRCh38/ensembl_grch38.exons.sorted.bed.gz"
#names=["ensembl_s","ensembl_e","ensembl_ov_id"]
#columns=[2,3,4]
#ops=["self","self","self"]

[[annotation]]
file="/home/aak64/rds/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources/CLINVAR/GRCh38/dbvar_grch38.CG.UR.CV.sorted.merged.gz"
names=["dbvar_s","dbvar_e","dbvar_ov_id"]
columns=[2,3,4]
ops=["self","self","self"]

[[annotation]]
file="/home/aak64/rds/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources/DECIPHER/GRCh38/decipher.grch38.sorted.merged.bed.gz"
names=["decipher_s","decipher_e","decipher_ov_id"]
columns=[2,3,4]
ops=["self","self","self"]

