[[annotation]]
file="/home/aak64/rds/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources/gnomad/GRCh37/r2.1.1/gnomad_grch37.AC.AN.AF.sorted.bed.gz"
names=["gnomad_s","gnomad_e","gnomad_ov_id"]
columns=[2,3,4]
ops=["self","self","self"]

[[annotation]]
file="/home/aak64/rds/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources/NGC_V1/GRCh37/NGC.samples.grch37.sorted.merged.bed.gz"
names=["ngc37_s","ngc37_e","ngc37_ov_id"]
columns=[2,3,4]
ops=["self","self","self"]

[[annotation]]
file="/home/aak64/rds/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources/CLINVAR/GRCh37/dbvar_grch37.CG.UR.CV.sorted.merged.gz"
names=["dbvar_s","dbvar_e","dbvar_ov_id"]
columns=[2,3,4]
ops=["self","self","self"]

[[annotation]]
file="/home/aak64/rds/rds-flr24-wgs10k-ngc/WGS10K/data/NGC/us/resources/DECIPHER/GRCh37/decipher.grch37.sorted.merged.bed.gz"
names=["decipher_s","decipher_e","decipher_ov_id"]
columns=[2,3,4]
ops=["self","self","self"]

